# Generated by Django 4.2.1 on 2023-06-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
