# Generated by Django 4.2.1 on 2023-06-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_personal_avatar'),
        ('customer', '0002_rename_create_at_job_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='customer_type',
        ),
        migrations.AddField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.personal'),
            preserve_default=False,
        ),
    ]
