# Generated by Django 4.2.1 on 2023-06-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_job_pickup_address_job_pickup_lat_job_pickup_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='pickup_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='job',
            name='pickup_lng',
            field=models.FloatField(default=0.0),
        ),
    ]
