# Generated by Django 4.2.1 on 2023-06-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('customer', '0009_job_delivered_at_job_delivery_photo_job_pickedup_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.courier'),
        ),
    ]
