# Generated by Django 4.2.1 on 2023-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('licence', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('businessname', models.CharField(max_length=20, unique=True)),
                ('businesssize', models.IntegerField()),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('username', models.CharField(default='xx234xx', max_length=10, unique=True)),
                ('lastname', models.CharField(max_length=10)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField()),
            ],
        ),
    ]
