# Generated by Django 4.2.1 on 2023-05-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
