# Generated by Django 4.2.1 on 2023-05-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_driver_email_alter_driver_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='mobile',
        ),
        migrations.AddField(
            model_name='personal',
            name='firstname',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='personal',
            name='password2',
            field=models.CharField(default='Personal.password', max_length=255),
        ),
    ]
