# Generated by Django 4.2.1 on 2023-05-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_personal_mobile_personal_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='password2',
        ),
    ]
