# Generated by Django 4.2.1 on 2023-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_driver_entreprise_alter_personal_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='businesssize',
            field=models.IntegerField(),
        ),
    ]
