# Generated by Django 4.2.1 on 2023-05-30 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_personal_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='businesssize',
        ),
    ]
