# Generated by Django 4.2.1 on 2023-05-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_driver_password_alter_entreprise_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='id',
        ),
        migrations.AddField(
            model_name='personal',
            name='username',
            field=models.CharField(default='xx234xx', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
