# Generated by Django 4.2.1 on 2023-05-31 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_delete_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('username', models.CharField(default='xx234xx', max_length=10, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
