# Generated by Django 4.2.1 on 2023-06-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_businessname_entreprise_business_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='licence',
            new_name='license',
        ),
    ]
