# Generated by Django 4.2.1 on 2023-06-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_licence_driver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personal',
            name='firstname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='personal',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personal',
            name='username',
            field=models.CharField(default='xx234xx', max_length=15, unique=True),
        ),
    ]
