# Generated by Django 4.2.1 on 2023-06-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_driver_firstname_alter_driver_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
