# Generated by Django 4.2.1 on 2023-06-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_driver_mobile_alter_entreprise_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customer/avatars/'),
        ),
    ]
