# Generated by Django 4.2.1 on 2023-06-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_personal_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='mobile',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
