# Generated by Django 4.2.1 on 2023-06-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_personal_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entreprise',
        ),
    ]
